[package]
name = "ipfs-embed-db"
version = "0.6.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "small embeddable ipfs implementation"
repository = "https://github.com/ipfs-rust/ipfs-embed"

[dependencies]
anyhow = "1.0.32"
futures = "0.3.5"
ipfs-embed-core = { version = "0.6.0", path = "../core" }
libipld = { version = "0.5.1", default-features = false }
log = "0.4.11"
parity-db = "0.1.2"
parity-scale-codec = "1.3.5"
serde = { version = "1.0.116", features = ["derive"] }
sled = "0.34.4"
thiserror = "1.0.20"
tiny-cid = { version = "0.2.5", features = ["scale-codec"] }

[dev-dependencies]
env_logger = "0.7.1"
libipld = { version = "0.5.1", features = ["dag-cbor"], default-features = false }
tempdir = "0.3.7"
