[package]
name = "ipfs-embed-net"
version = "0.6.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "small embeddable ipfs implementation"
repository = "https://github.com/ipfs-rust/ipfs-embed"

[dependencies]
async-std = "1.6.3"
futures = "0.3.5"
ip_network = "0.3.4"
ipfs-embed-core = { version = "0.6.0", path = "../core" }
libp2p-bitswap = "0.7.0"
log = "0.4.11"
names = "0.11.0"
thiserror = "1.0.20"

[dependencies.libp2p]
version = "0.28.1"
default-features = false
features = ["identify", "kad", "mdns-async-std", "mplex", "noise", "ping", "tcp-async-std", "yamux"]
